import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Auction.module.css';

const Auction: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LostArk Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.button_container}>
        <button>+ 5000</button>
        <button>+ 1000</button>
        <button>+ 500</button>
        <button>+ 100</button>
      </div>
    </div>
  );
};

export default Auction;
