import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LostArk Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/calculator.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>LostArk Calculator</h1>

        <p className={styles.description}>
          Get started by click{' '}
          <span className={styles.here}>
            <Link href="/auction">HERE</Link>
          </span>
        </p>
      </main>
    </div>
  );
};

export default Home;
