import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Auction.module.css';
import React, { useState, useEffect } from 'react';
import 'react-toastify/dist/ReactToastify.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

const Ticket: NextPage = () => {
  return (
    <div className={styles.container}>
      <div className={styles.box}>
        <Head>
          <title>LostArk Calculator</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/calculator.ico" />
        </Head>
      </div>
    </div>
  );
};

export default Ticket;
